export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const GET_TOPCRYPTOS_FETCHING = 'GET_TOP_CRYPTOS_FETCHING';
export const GET_TOPCRYPTOS_SUCCESS = 'GET_TOP_CRYPTOS_SUCCESS';